apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "Root@123"
  MYSQL_REPLICATION_PASSWORD: "Repl@123"      # used by both primary & replicas
  MYSQL_APP_PASSWORD: "App@123"               # for appuser
